### ISSUE TITLE
transpiling globalThis ponyfill to ES5

### ISSUE THREAD

**Issue by mvasin** [Offirmo/offirmo-monorepo#3]
Hi @Offirmo!
Can you please also transpile the `globalThis` ponyfill to ES5? Otherwise I can't use it in https://github.com/baruchvlz/resq/pull/56.

**Comment by Offirmo** [comment]
Hi @mvasin, I'm honored that you selected my module.

My current transpiling policy is documented here: https://github.com/Offirmo/offirmo-monorepo/blob/master/CONTRIBUTING/module-exports.md (not very readable, I'll improve that)

Transpiling to ES5 is a controversial topic, since "ES5" as it is not an existing running platform. I believe you mean "IE11". Since every project has different platform requirements, transpiling to "ES5"/IE11 is not efficient, it would downgrade too much.

That's why I decided to offer a "latest stable ECMA" default version + a transpiled "latest stable node" as a convenience for node/unit tests. More than that takes a lot of time to maintain on my side.

My opinion is that the end user is responsible of the target selection and thus should transpile its dependencies accordingly. I understand that not everyone thinks the same.

**Comment by mvasin** [comment]
Thanks for the response!

I thought the convention was "don't transpile node_modules". But I understand that there are infinite variations of possible transpilation settings, and using the lowest common denominator (ES5) may not be the most efficient.

I'll look into transpiling node_modules.
